lokikirja/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lokikirja_app.urls')),
]

lokikirja_app/urls.py
from django.urls import path
from . import views

app_name = 'lokikirja_app'

urlpatterns = [
    path('accounts/login/', views.login_view, name='login'),
    path('accounts/register/', views.register, name='register'),
    path('', views.index, name='index'),
    path('create_event/', views.create_event, name='create_event'),
    path('logbook/<int:event_id>/', views.logbook_detail, name='logbook_detail'),
    path('toggle_mirror/<int:logbook_id>/', views.toggle_mirror, name='toggle_mirror'),

]

lokikirja_app/models.py
from django.contrib.auth.models import User
from django.db import models

class Event(models.Model):
    # Tapahtuman nimi, joka on enintään 100 merkkiä pitkä
    name = models.CharField(max_length=100)
    # Tapahtuman luontipäivämäärä ja -aika, tallentuu automaattisesti kun tapahtuma luodaan
    created_at = models.DateTimeField(auto_now_add=True)
    
class Logbook(models.Model):
    # Viittaus tapahtumaan, johon tämä lokikirja kuuluu
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    # Viittaus käyttäjään, joka loi tämän lokikirjan
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # Lokikirjan luontipäivämäärä ja -aika, tallentuu automaattisesti kun lokikirja luodaan
    created_at = models.DateTimeField(auto_now_add=True)
    # Peilataanko lokikirja?
    mirror = models.BooleanField(default=False)

class LogEntry(models.Model):
    # Viittaus lokikirjaan, johon lokimerkintä kuuluu
    logbook = models.ForeignKey(Logbook, on_delete=models.CASCADE, related_name='log_entries')
    # Lokimerkinnän viesti, asetettu viestin enimmäispituudeksi 10 000 merkkiä väärinkäyttöjen välttämiseksi.
    message = models.TextField(max_length=10000)
    # Viittaus käyttäjään, joka loi tämän lokimerkinnän
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='log_entries')
    # Lokimerkinnän luontipäivämäärä ja luontiaika, tallentuu automaattisesti kun lokimerkintä luodaan
    created_at = models.DateTimeField(auto_now_add=True)

class MirrorLogbook(models.Model):
    # Viittaus käyttäjään, joka omistaa tämän peililokikirjan
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # mitkä lokikirjat peilataan
    mirrored_logbooks = models.ManyToManyField(Logbook)

lokikirja_app/forms.py
from django import forms
from .models import Event

class LogbookPostForm(forms.Form):
    message = forms.CharField(label="", widget=forms.Textarea(attrs={'placeholder': 'Lisää loki'}))
    
class EventForm(forms.ModelForm):
    name = forms.CharField(label='Nimi')
    class Meta:
        model = Event
        fields = ['name']

lokikirja_app/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from .models import Event, LogEntry, Logbook, MirrorLogbook
from .forms import EventForm, LogbookPostForm

def login_view(request):
    """Käsittelee käyttäjän kirjautumisen.

    Käyttäjä täyttää lomakkeen tiedot ja lähettää ne. Jos tiedot ovat kelvolliset,
    käyttäjä kirjataan sisään. Jos tiedot eivät ole kelvolliset, näytetään virheviesti.

    Args:
        request: Pyynnön olio.

    Returns:
        Palauttaa käyttäjän etusivulle jos kirjautuminen onnistui, 
        muutoin palautetaan takaisin kirjautumissivulle.
    """
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("/")
            else:
                return render(request, "lokikirja_app/login.html", {"form": form})
        else:
            return render(request, "lokikirja_app/login.html", {"form": form})
    else:
        form = AuthenticationForm()
        return render(request, "lokikirja_app/login.html", {"form": form})

def register(request):
    """Käsittelee käyttäjän rekisteröitymisen.

    Käyttäjä täyttää lomakkeen tiedot ja lähettää ne. Jos tiedot ovat kelvolliset, 
    luodaan uusi käyttäjä ja kirjataan käyttäjä sisään. Jos tiedot eivät ole kelvolliset, 
    näytetään virheviesti.

    Args:
        request: Pyynnön olio.

    Returns:
        Ohjaa käyttäjän etusivulle jos rekisteröityminen onnistui, 
        muutoin palautetaan takaisin rekisteröitymissivulle.
    """
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            MirrorLogbook.objects.create(user=user)
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/')
        else:
            messages.error(request, 'Virhe kirjautumisessa, tarkasta salasanavaatimukset.')
    else:
        form = UserCreationForm()
    return render(request, 'lokikirja_app/register.html', {'form': form})


@login_required
def index(request):
    """Näyttää kaikki tapahtumat.

    Args:
        request: Pyynnön olio.

    Returns:
        Renderöi index-sivun, jossa näytetään kaikki tapahtumat.
    """
    events = Event.objects.all()
    return render(request, "lokikirja_app/index.html", {"events": events})


@login_required
def create_event(request):
    """Luo uuden tapahtuman.

    Args:
        request: Pyynnön olio.

    Returns:
        Palauttaa käyttäjän etusivulle jos tapahtuman luominen onnistui, 
        muutoin palautetaan takaisin tapahtuman luomissivulle.
    """
    if request.method == "POST":
        form = EventForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("lokikirja_app:index")
    else:
        form = EventForm()

    return render(request, "lokikirja_app/create_event.html", {"form": form})


@login_required
def logbook_detail(request, event_id):
    """Näyttää tietyn lokikirjan tiedot.

    Args:
        request: Pyynnön olio.
        event_id: Tapahtuman id.

    Returns:
        Renderöi logbook_detail-sivun, jossa näytetään tietyn lokikirjan tiedot.
    """
    # Hae tapahtuma tai palauta 404-virhe, jos sitä ei ole olemassa
    event = get_object_or_404(Event, id=event_id)

    user = request.user
    logbook = Logbook.objects.filter(event=event, user=user).first()

    # Jos käyttäjä avaa eventin ensimmäistä kertaa luodaan uusi lokikirja
    if not logbook:
        logbook = Logbook.objects.create(event=event, user=user)

    form = LogbookPostForm()
    if request.method == "POST":
        form = LogbookPostForm(request.POST)
        if form.is_valid():
            message = form.cleaned_data["message"]
            LogEntry.objects.create(logbook=logbook, user=user, message=message)
            return redirect("lokikirja_app:logbook_detail", event_id=event_id)

    logbooks = Logbook.objects.filter(event=event)
    mirror_logbook = MirrorLogbook.objects.get(user=user)
    mirrored_logbooks = mirror_logbook.mirrored_logbooks.filter(event=event)
    # Hae ja järjestä kaikki logbookin merkinnät luontiajan mukaan
    logbook_entries = logbook.log_entries.all().order_by('created_at')

    for mirrored_logbook in mirrored_logbooks:
        if mirrored_logbook.event == event:
            logbook_entries = logbook_entries | mirrored_logbook.log_entries.all().order_by('created_at')

    return render(
        request,
        "lokikirja_app/logbook_detail.html",
        {
            "logbook_entries": logbook_entries,
            "form": form,
            "event": event,
            "logbooks": logbooks,
        },
    )


@login_required
def toggle_mirror(request, logbook_id):
    """Asettaa tai poistaa peilauksen valitusta lokikirjasta.

    Args:
        request: Pyynnön olio.
        logbook_id: Lokikirjan id.

    Returns:
        Uudelleenohjaus takaisin logbook_detail-näkymään.
    """
    logbook = get_object_or_404(Logbook, id=logbook_id)
    mirror_logbook, _ = MirrorLogbook.objects.get_or_create(user=request.user)
    if logbook in mirror_logbook.mirrored_logbooks.all():
        mirror_logbook.mirrored_logbooks.remove(logbook)
    else:
        mirror_logbook.mirrored_logbooks.add(logbook)
    return redirect("lokikirja_app:logbook_detail", event_id=logbook.event.id)

lokikirja_app/templates/lokikirja_app/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'lokikirja_app/style.css' %}">
</head>
<body>
  <div id="center">
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

lokikirja_app/templates/lokikirja_app/create_event.html
{% extends 'lokikirja_app/base.html' %}

{% block content %}
    <h2>Luo uusi tapahtuma</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Luo Tapahtuma</button>
    </form>
{% endblock %}

lokikirja_app/templates/lokikirja_app/index.html
{% extends 'lokikirja_app/base.html' %}

{% block content %}
  <h1>Lokikirjasovelluksen proof of concept</h1>
  <p>Olet kirjautunut sisään käyttäjänä: {{ user }} <p>
  <h2>Kaikki tapahtumat</h2>
  {% if events %}
    <ul class="events">
      {% for event in events %}
        <li class="event_links"><a href="{% url 'lokikirja_app:logbook_detail' event.id %}">{{ event.name }}</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <p>Ei tapahtumia.</p>
  {% endif %}

  <br>

  <form method="post" action="{% url 'lokikirja_app:create_event' %}">
    {% csrf_token %}
    <button type="submit">Luo uusi tapahtuma</button>
  </form>

{% endblock %}

lokikirja_app/templates/lokikirja_app/logbook_detail.html
{% extends 'lokikirja_app/base.html' %}

{% block content %}

<div class="navbar">
  <a href="{% url 'lokikirja_app:index' %}">Koti</a>
  <div class="dropdown">
    <button class="dropbtn" onclick="toggleDropdown()">Lokikirjat
      <i class="fa fa-caret-down"></i>
    </button>
    <div id="dropdown-content" class="dropdown-content">
      <h3>Tapahtuman Lokikirjat</h3>
      <ul>
      {% for logbook in logbooks %}
        <li>
          <div style="display: flex; align-items: center;">
            <div>
              {{ logbook.user }} - {{ logbook.created_at }}
            </div>
            {% if logbook.user != user %}
              <form method="POST" style="margin-left: 10px;" action="{% url 'lokikirja_app:toggle_mirror' logbook.id %}">
                {% csrf_token %}
                <input id="mirror-{{ logbook.id }}" type="checkbox" onchange="this.form.submit()" {% if logbook in user.mirrorlogbook.mirrored_logbooks.all %}checked{% endif %}>
              </form>
            {% endif %}
          </div>
        </li>
      {% empty %}
        <li>Ei muita lokikirjoja.</li>
      {% endfor %}
      </ul>
    </div>
  </div> 
</div>


  <h1>{{ event.name }}</h1>
  <p>luotu: {{ event.created_at }}</p>
  <br>

  <h3>Lokit</h3>
  {% for entry in logbook_entries %}
    {% if entry.logbook.user != user %}
      <li class="mirrored_log_entries"><strong>{{ entry.created_at|date:"F d, Y H:i:s" }} {{entry.user}}</strong> <br> - {{ entry.message }} </li>
    {% else %}
      <li class="log_entries"><strong>{{ entry.created_at|date:"F d, Y H:i:s" }} {{entry.user}}</strong> <br> - {{ entry.message }} </li>
    {% endif %}
{% empty %}
    <li>Ei lokeja.</li>
{% endfor %}

  <h3>Lisää loki</h3>
  <form method="POST" action="{% url 'lokikirja_app:logbook_detail' event_id=event.id %}" class="logbook-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="submit-button">Lisää</button>
  </form>


  
  <h3>Tapahtuman Lokikirjat</h3>
  <ul>
  {% for logbook in logbooks %}
    <li>
      <div style="display: flex; align-items: center;">
        <div>
          {{ logbook.user }} - {{ logbook.created_at }}
        </div>
        {% if logbook.user != user %}
          <form method="POST" style="margin-left: 10px;" action="{% url 'lokikirja_app:toggle_mirror' logbook.id %}">
            {% csrf_token %}
            <input id="mirror-{{ logbook.id }}" type="checkbox" onchange="this.form.submit()" {% if logbook in user.mirrorlogbook.mirrored_logbooks.all %}checked{% endif %}>
          </form>
        {% endif %}
      </div>
    </li>
  {% empty %}
    <li>Ei muita lokikirjoja.</li>
  {% endfor %}
  </ul>

  <script>
    function toggleDropdown() {
      document.getElementById("dropdown-content").classList.toggle("show");
    }
    
    // Sulje pudotusvalikko, jos käyttäjä napsauttaa sen ulkopuolella
    window.onclick = function(event) {
      if (!event.target.matches('.dropbtn')) {
        var dropdowns = document.getElementsByClassName("dropdown-content");
        var i;
        for (i = 0; i < dropdowns.length; i++) {
          var openDropdown = dropdowns[i];
          if (openDropdown.classList.contains('show')) {
            openDropdown.classList.remove('show');
          }
        }
      }
    }
    
  </script>
{% endblock %}

lokikirja_app/templates/lokikirja_app/login.html
{% extends 'lokikirja_app/base.html' %}

{% block content %}
<div id="center">
<h2>Kirjaudu sisään</h2>
  <form method="post" action="{% url 'lokikirja_app:login' %}">
    <br>
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary" type="submit">Kirjaudu sisään</button>
  </form>
  <p>Uusi käyttäjä</p>
  <a class="btn-register-link" href="{% url 'lokikirja_app:register' %}">Rekisteröidy</a>
</div>
{% endblock %}

lokikirja_app/templates/lokikirja_app/register.html
{% extends 'lokikirja_app/base.html' %}

{% block content %}
<div id="center">
    <h2>Rekisteröidy</h2>
    
    {% for message in messages %}
    <p class="alert {{ message.tags }}">{{ message }}</p>
    {% endfor %}
    
    <form method="post" action="{% url 'lokikirja_app:register' %}">
    {% csrf_token %}
    {% for field in form %}
    <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
        <small style="color: grey;">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
        <p style="color: red;">{{ error }}</p>
        {% endfor %}
    </p>
    {% endfor %}
    <button class="btn btn-primary" type="submit">Rekisteröidy</button>
    </form>
    <p>Olen jo rekisteröitynyt</p>
    <a class="btn-login-link" href="{% url 'lokikirja_app:login' %}">Kirjaudu sisään</a>
</div>
{% endblock %}